# Problem 2: Even Fibonacci numbers
# Even Fibonacci numbers
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, 
# the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fab(num1,num2,sumofnum,result):
    if(sumofnum<4000000):
        sumofnum = num1 + num2
        if sumofnum%2==0:
            value.append(sumofnum)
        num1 = num2
        num2 = sumofnum
        fab(num1,num2,sumofnum,result)
    return sum(value)
value = [2]
answer = fab(1,2,0,2)
print(answer)
